name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  # ideally we should not deploy all together and rather deploy all three separately
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH Into server
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh-keyscan -H 13.61.155.151 >> ~/.ssh/known_hosts
          ssh -i ~/ssh_key ubuntu@13.61.155.151 '
            cd ~/devops100xdevs-week25.2 && \
            git pull && \
            yarn install && \
            yarn run build && \
            pm2 restart http-server && \
            pm2 restart fe-server && \
            pm2 restart ws-server
          '

