name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 13.61.155.151 >> ~/.ssh/known_hosts

      - name: Deploy to staging server
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@13.61.155.151 '
            cd ~/devops100xdevs-week25.2 && \
            git pull origin main && \
            yarn install --frozen-lockfile && \
            yarn build && \
            pm2 restart http-server && \
            pm2 restart fe-server && \
            pm2 restart ws-server
          '

